apiVersion: v1
kind: Namespace
metadata:
  name: bolsa-dev
  labels:
    app.kubernetes.io/part-of: bolsa-atleta
    environment: dev
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-dev
  namespace: bolsa-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    pods: "30"
